version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: workouts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d workouts"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"

  stats:
    build: ./stats-service
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/workouts
      TIMEZONEDB_API_KEY: ${TIMEZONEDB_API_KEY}
      DEFAULT_TZ: Europe/Ljubljana
    depends_on:
      - db
    ports:
      - "5001:5000"

  core:
    build: ./app-service
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/workouts
      STATS_SERVICE_URL: http://stats:5000
      SECRET_KEY: ${SECRET_KEY}
      FLASK_APP: app.py
    depends_on:
      db:
        condition: service_healthy
      stats:
        condition: service_started
    ports:
      - "25565:25565"

volumes:
  pgdata:
