apiVersion: v1
kind: Secret
metadata:
  name: liftlog-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  TIMEZONEDB_API_KEY: {{ .Values.secrets.timezonedbApiKey | quote }}
