apiVersion: v1
kind: Service
metadata:
  name: stats
  namespace: {{ .Release.Namespace }}
  labels:
    app: stats
spec:
  type: {{ .Values.stats.service.type }}
  selector:
    app: stats
  ports:
  - name: http
    port: {{ .Values.stats.service.port }}
    targetPort: 5000