apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: liftlog-core
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: core
  namespaceSelector:
    matchNames:
      - liftlog
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: liftlog-stats
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: stats
  namespaceSelector:
    matchNames:
      - liftlog
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
